version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: reasearch-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
      
  metabase:
    image: metabase/metabase
    container_name: reasearch-metabase
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
